using System.IO;
using Microsoft.CodeAnalysis;

namespace Brew.Features.SourceGenerators;

/// <summary>
/// A sample source generator that creates C# classes based on the text file (in this case, Domain Driven Design ubiquitous language registry).
/// Converted to an incremental source generator.
/// </summary>
[Generator]
public sealed class SampleSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var contentProvider = context.AdditionalTextsProvider
            .Where(static a => Path.GetFileName(a.Path) == "DDD.UbiquitousLanguageRegistry.txt")
            .Select(static (a, ct) => a.GetText(ct)?.ToString() ?? string.Empty);

        context.RegisterSourceOutput(contentProvider, static (ctx, content) =>
        {
            if (string.IsNullOrWhiteSpace(content))
                return;

            using var reader = new StringReader(content);
            string? line;
            while ((line = reader.ReadLine()) is not null)
            {
                var className = line.Trim();
                if (string.IsNullOrWhiteSpace(className))
                    continue;

                string source = $@"// <auto-generated/>

namespace Entities
{{
    public partial class {className}
    {{
    }}
}}
";
                ctx.AddSource($"{className}.g.cs", source);
            }
        });
    }
}